<a href="https://colab.research.google.com/github/arman-hossain45/Recurrent_Neural_Network/blob/main/gk_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
print('Rnn is build  for sequential data and unlike traditional feed forward data in details  ')

Rnn is build  for sequential data and unlike traditional feed forward data in details  


#Simple gk system rnn project

In [40]:
import pandas as pd
import re

In [41]:
df=pd.read_csv('qna.csv')

In [42]:
df.head(4)

,question,answer
0,"What is the capital of ""France""?",Paris
1,"What is the capital of ""Germany""?",Berlin
2,"What is the capital of ""Italy""?",Rome
3,"What is the capital of ""Spain""?",Madrid


In [43]:
df['question'][0]

'What is the capital of "France"?'

We want to read only clean text we remove double quatation and comma and hash we wnat to remove this in our text data so that we apply differnt types of methods to remove all of this in details

In [44]:
# tokenize with regular expression
def tokenize(text):
  # Lowercase
  text =text.lower()

  # Remove quotes
  text = re.sub(r"['\"]","",text)
  # single quatation and double quotes remove hoye jabe

  #Remove all punctuation
  text = re.sub(r"[^a-z0-9\s]", " ", text)

  # remove extra space
  text = re.sub(r"\s+"," ",text).strip()

  #tokenize split into words
  tokens = text.split()
  return tokens

In [45]:

print(tokenize(df['question'][0]))

['what', 'is', 'the', 'capital', 'of', 'france']


# Vocab forming

In [46]:
vocab = {'<UNK>':0}
def build_vocab(row):
  print(row['question'],row['answer'])
  tokenize_question = tokenize(row['question'])
  tokenize_answer =  tokenize(row['answer'])
  #print(tokenize_question,tokenize_answer)
  merge_tokens = tokenize_question + tokenize_answer
 # print(merge_tokens)

  for token in merge_tokens:
    if token not in vocab :
      vocab[token]= len(vocab)


In [47]:
df.apply(build_vocab,axis=1)

What is the capital of "France"? Paris
What is the capital of "Germany"? Berlin
What is the capital of "Italy"? Rome
What is the capital of "Spain"? Madrid
What is the capital of "Japan"? Tokyo
What is the capital of "Canada"? Ottawa
What is the capital of "Brazil"? Brasilia
What is the capital of "Australia"? Canberra
What is the capital of "India"? New Delhi
What is the capital of "China"? Beijing
What is the capital of "Russia"? Moscow
What is the capital of "United States"? Washington DC
What is the capital of "Mexico"? Mexico City
What is the capital of "Egypt"? Cairo
What is the capital of "Turkey"? Ankara
What is the capital of "Argentina"? Buenos Aires
What is the capital of "South Korea"? Seoul
What is the capital of "Indonesia"? Jakarta
What is the capital of "Pakistan"? Islamabad
What is the capital of "Bangladesh"? Dhaka
What is the capital of "Nepal"? Kathmandu
What is the capital of "Sri Lanka"? Colombo
What is the capital of "Thailand"? Bangkok
What is the capital of "Ma

,0
0,None
1,None
2,None
3,None
4,None
...,...
166,None
167,None
168,None
169,None


In [48]:
vocab# ai khan a muloto unique value gula akta unique index value paise

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq

In [49]:
len(vocab)

243

# text to indices

In [50]:
def text_to_indices(text,vocab):
  indexed = []
  for token in tokenize(text):
    if token in vocab:
      #print(vocab[token])
      indexed.append(vocab[token])

    else :
      indexed.append(vocab['<UNK>'])
  return indexed

In [51]:
text_to_indices("what is arman",vocab)

[1, 2, 0]

Here we see that arman is unknown so that it define arman as 0 index

In [52]:
text_to_indices("the capital of",vocab)

[3, 4, 5]

# Data set and dataloader

In [53]:
import torch
from torch.utils.data import Dataset,DataLoader

In [54]:
index= 0
text_to_indices(df.iloc[index]['question'],vocab)

[1, 2, 3, 4, 5, 6]

In [55]:
class QADataset(Dataset):

  def __init__(self,df,vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,index):
   num_qus= text_to_indices(self.df.iloc[index]['question'],self.vocab)
   num_ans= text_to_indices(self.df.iloc[index]['answer'],self.vocab)
   return torch.tensor(num_qus),torch.tensor(num_ans)


In [56]:
dataset = QADataset(df,vocab)
dataset[1]

(tensor([1, 2, 3, 4, 5, 8]), tensor([9]))

In [57]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [58]:
for question,answer in dataloader:
  print(question,answer)

tensor([[ 1,  2,  3,  4,  5, 51]]) tensor([[52]])
tensor([[ 1,  2,  3,  4,  5, 35]]) tensor([[36]])
tensor([[ 1,  2,  3,  4,  5, 61]]) tensor([[62]])
tensor([[230, 231,  93, 209,   2, 210, 211, 212, 213]]) tensor([[214]])
tensor([[237,   1, 238, 239,  79, 114,   3, 115,   5, 116]]) tensor([[117, 118]])
tensor([[230, 231,   1,   2, 124, 120, 121]]) tensor([[125, 126]])
tensor([[ 93, 179,   2, 101, 102,   3, 180,   5, 181, 182,  95, 232, 233]]) tensor([[14]])
tensor([[234, 235, 236,   1,   2,  89,  90,  91]]) tensor([[92]])
tensor([[240, 232, 241, 242,   1,   2, 124, 120, 121]]) tensor([[125, 126]])
tensor([[ 93,  94,  95, 206, 207]]) tensor([[208]])
tensor([[237,   1, 238, 239,  79,  80,  81]]) tensor([[82, 83]])
tensor([[240, 232, 241, 242,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([[104]])
tensor([[240, 232, 241, 242,   1,   2, 119, 120, 121]]) tensor([[122, 123]])
tensor([[237,   1, 238, 239,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([[104]])
tensor([[ 93, 183,   2,  91

# RNN architeccture

In [59]:
# squeez
x = torch.tensor([[[1,2,3]]])
print(x.shape)
y= x.squeeze(0)
print(y.shape)

torch.Size([1, 1, 3])
torch.Size([1, 3])


In [60]:
import torch.nn as nn

class RNN(nn.Module):
  def __init__(self,vocab_size,embedding_dim=50,hidden_size=64):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,embedding_dim)
    self.rnn = nn.RNN(embedding_dim,hidden_size,batch_first=True)
    self.fc = nn.Linear(hidden_size,vocab_size)

  def forward(self,question):
    embedded = self.embedding(question)
    _, final_hidden_state = self.rnn(embedded)
    # final_hidden_state has shape (num_layers * num_directions, batch_size, hidden_size)
    # For a single-layer, unidirectional RNN, this is (1, batch_size, hidden_size)
    # We need to squeeze out the first dimension before passing to the linear layer
    return self.fc(final_hidden_state.squeeze(0)) # (batch_size, vocab_size)

In [61]:
model=RNN(vocab_size=len(vocab))

#Tranning loop

In [62]:


criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.0001)
epochs = 50


for epoch in range(epochs):
    total_loss = 0
    for question, answer in dataloader:
        optimizer.zero_grad()
        output = model(question)
        # Fix: take only the first answer token as target → shape (1,)
        target = answer[0][0].unsqueeze(0)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}/{epochs}  |  Loss: {total_loss:.4f}")

Epoch  10/50  |  Loss: 586.2246
Epoch  20/50  |  Loss: 355.5586
Epoch  30/50  |  Loss: 235.6163
Epoch  40/50  |  Loss: 164.9839
Epoch  50/50  |  Loss: 116.0979


Prediction of this model and see  the performance

In [63]:
vocab.items()

dict_items([('<UNK>', 0), ('what', 1), ('is', 2), ('the', 3), ('capital', 4), ('of', 5), ('france', 6), ('paris', 7), ('germany', 8), ('berlin', 9), ('italy', 10), ('rome', 11), ('spain', 12), ('madrid', 13), ('japan', 14), ('tokyo', 15), ('canada', 16), ('ottawa', 17), ('brazil', 18), ('brasilia', 19), ('australia', 20), ('canberra', 21), ('india', 22), ('new', 23), ('delhi', 24), ('china', 25), ('beijing', 26), ('russia', 27), ('moscow', 28), ('united', 29), ('states', 30), ('washington', 31), ('dc', 32), ('mexico', 33), ('city', 34), ('egypt', 35), ('cairo', 36), ('turkey', 37), ('ankara', 38), ('argentina', 39), ('buenos', 40), ('aires', 41), ('south', 42), ('korea', 43), ('seoul', 44), ('indonesia', 45), ('jakarta', 46), ('pakistan', 47), ('islamabad', 48), ('bangladesh', 49), ('dhaka', 50), ('nepal', 51), ('kathmandu', 52), ('sri', 53), ('lanka', 54), ('colombo', 55), ('thailand', 56), ('bangkok', 57), ('malaysia', 58), ('kuala', 59), ('lumpur', 60), ('vietnam', 61), ('hanoi', 62

In [64]:
# ind to word mapping
index_to_word = {idx : word for word,idx in vocab.items()}
index_to_word

{0: '<UNK>',
 1: 'what',
 2: 'is',
 3: 'the',
 4: 'capital',
 5: 'of',
 6: 'france',
 7: 'paris',
 8: 'germany',
 9: 'berlin',
 10: 'italy',
 11: 'rome',
 12: 'spain',
 13: 'madrid',
 14: 'japan',
 15: 'tokyo',
 16: 'canada',
 17: 'ottawa',
 18: 'brazil',
 19: 'brasilia',
 20: 'australia',
 21: 'canberra',
 22: 'india',
 23: 'new',
 24: 'delhi',
 25: 'china',
 26: 'beijing',
 27: 'russia',
 28: 'moscow',
 29: 'united',
 30: 'states',
 31: 'washington',
 32: 'dc',
 33: 'mexico',
 34: 'city',
 35: 'egypt',
 36: 'cairo',
 37: 'turkey',
 38: 'ankara',
 39: 'argentina',
 40: 'buenos',
 41: 'aires',
 42: 'south',
 43: 'korea',
 44: 'seoul',
 45: 'indonesia',
 46: 'jakarta',
 47: 'pakistan',
 48: 'islamabad',
 49: 'bangladesh',
 50: 'dhaka',
 51: 'nepal',
 52: 'kathmandu',
 53: 'sri',
 54: 'lanka',
 55: 'colombo',
 56: 'thailand',
 57: 'bangkok',
 58: 'malaysia',
 59: 'kuala',
 60: 'lumpur',
 61: 'vietnam',
 62: 'hanoi',
 63: 'uae',
 64: 'abu',
 65: 'dhabi',
 66: 'iran',
 67: 'tehran',
 68: '

In [68]:

idx_to_word = { idx : word for word,idx in vocab.items()  }
idx_to_word

{0: '<UNK>',
 1: 'what',
 2: 'is',
 3: 'the',
 4: 'capital',
 5: 'of',
 6: 'france',
 7: 'paris',
 8: 'germany',
 9: 'berlin',
 10: 'italy',
 11: 'rome',
 12: 'spain',
 13: 'madrid',
 14: 'japan',
 15: 'tokyo',
 16: 'canada',
 17: 'ottawa',
 18: 'brazil',
 19: 'brasilia',
 20: 'australia',
 21: 'canberra',
 22: 'india',
 23: 'new',
 24: 'delhi',
 25: 'china',
 26: 'beijing',
 27: 'russia',
 28: 'moscow',
 29: 'united',
 30: 'states',
 31: 'washington',
 32: 'dc',
 33: 'mexico',
 34: 'city',
 35: 'egypt',
 36: 'cairo',
 37: 'turkey',
 38: 'ankara',
 39: 'argentina',
 40: 'buenos',
 41: 'aires',
 42: 'south',
 43: 'korea',
 44: 'seoul',
 45: 'indonesia',
 46: 'jakarta',
 47: 'pakistan',
 48: 'islamabad',
 49: 'bangladesh',
 50: 'dhaka',
 51: 'nepal',
 52: 'kathmandu',
 53: 'sri',
 54: 'lanka',
 55: 'colombo',
 56: 'thailand',
 57: 'bangkok',
 58: 'malaysia',
 59: 'kuala',
 60: 'lumpur',
 61: 'vietnam',
 62: 'hanoi',
 63: 'uae',
 64: 'abu',
 65: 'dhabi',
 66: 'iran',
 67: 'tehran',
 68: '

In [69]:


def predict(question_text,model,vocab,idx_to_word):
  model.eval()

  with torch.no_grad():
    indices = text_to_indices(question_text,vocab)

    if not indices:
      return ""

    x = torch.tensor(indices).unsqueeze(0)  #batch size, sequence legth

    pred = torch.argmax(model(x),dim=1).item()


  return idx_to_word.get(pred,"")

In [70]:

# Test
tests = [
    "What is the capital of France?",
    "What is H2O commonly called?",
    "Which planet is known as the red planet?",
    "Which bird cannot fly?",
    "What is the capital of Japan ?",

]
for q in tests:
    print(f"{q:45} → {predict(q, model, vocab, idx_to_word)}")

What is the capital of France?                → paris
What is H2O commonly called?                  → water
Which planet is known as the red planet?      → mars
Which bird cannot fly?                        → ostrich
What is the capital of Japan ?                → tokyo
